version: '3.9'
services:
  apollo-router-otel-http:
    image: ghcr.io/apollographql/router:v1.19.1
    volumes:
      - ./supergraph-schema.graphql:/etc/config/supergraph.graphql
      - ./router-otel-http.yaml:/etc/config/router.yaml
    command:
      [
        '-c',
        '/etc/config/router.yaml',
        '-s',
        '/etc/config/supergraph.graphql',
        '--log',
        'info',
        '--hot-reload',
      ]
    ports:
      - 4001:4001
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - PORT=4001
      - SANDBOX=true
      - OTEL_COLLECTOR_ENDPOINT=http://otel-collector:4318/v1/traces

  apollo-router-otel-grpc:
    image: ghcr.io/apollographql/router:v1.19.1
    volumes:
      - ./supergraph-schema.graphql:/etc/config/supergraph.graphql
      - ./router-otel-grpc.yaml:/etc/config/router.yaml
    command:
      [
        '-c',
        '/etc/config/router.yaml',
        '-s',
        '/etc/config/supergraph.graphql',
        '--log',
        'info',
        '--hot-reload',
      ]
    ports:
      - 4000:4000
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - PORT=4000
      - SANDBOX=true
      - OTEL_COLLECTOR_ENDPOINT=otel-collector:4317

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ['--config=/etc/otel-collector-config.yaml']
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - '4317:4317' # OTLP gRPC receiver
      - '4318:4318'
    depends_on:
      - zipkin

  # Zipkin
  zipkin:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - '9411:9411'

  # small node app
  node-app:
    image: node:18-alpine
    working_dir: /app
    command: >
      sh -c "npm install && npm start"
    volumes:
      - ./node-app:/app
    ports:
      - 8091:8091
    
    environment:
      - OTLP_TRACING_URL=http://otel-collector:4318/v1/traces
      - OTLP_METRICS_URL=http://otel-collector:4318/v1/metrics
      - PORT=8091
