receivers:
  otlp:
    protocols:
      grpc:
      http:
        include_metadata: true
        cors:
          allowed_origins:
            - '*'

  otlp/spanmetrics:
    protocols:
      grpc:
        endpoint: 0.0.0.0:12346

exporters:
  zipkin:
    endpoint: 'http://zipkin:9411/api/v2/spans'
    format: proto

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin]

  telemetry:
    logs:
      level: "debug"
